### ISSUE TITLE
Any way to know when user logged out of FB?

### ISSUE THREAD

**Issue by diversario** [DracoBlue/node-facebook-client#7]
I can't figure out how to detect that user has logged out from Facebook without calling isValid() on every request. In my case, I keep getting valid session from getSessionByRequestHeaders() even if I log out of Facebook. I have to actually delete Facebook cookies to see that session is undefined.

**Comment by DracoBlue** [comment]
Yes, the session is still valid since it's validated by the facebook session timeout in the cookie. Since a logout at facebook isn't capable to remove all cookies for all partner sites, the only way is to call isValid when necessary.

If you want to automaticly refresh as soon as the user logged out of facebook, you may use this on clientside:

```
FB.Event.subscribe('auth.sessionChange', function(response) {
    document.location = document.location.href;
});
```

This will also remove the cookie.

Another workaround may be to check the isValid only after a specific time.

Regards,
  Jan

**Comment by diversario** [comment]
Yeah, I forgot about `FB.Event.subscribe`, thanks!
