### ISSUE TITLE
Avoid double-checking returned values

### ISSUE THREAD

**Issue by diversario** [DracoBlue/node-facebook-client#8]
Currently, `FacebookClient#getSessionByRequestHeaders()` returns either a session object or `undefined`. At the same time, `FacebookSession#isValid()` is supposed to be called on a session object that's returned by `getSessionByRequestHeaders` method. If user is not logged in - calling `isValid` throws a TypeError.

I suggest that `getSessionByRequestHeaders` should return something that `isValid` can be called on regardless of login status. This way, there would be no need to check if session is not `undefined` before attempting to validate it.

**Comment by DracoBlue** [comment]
The issue is, that each call to isValid costs a GET-request to the Facebook servers. The only case when the returned session by getSessionByRequestHeaders is invalid, is: when the user logged out on your page without your page knowing.

You could check this also clientside, with this snippet:

```
FB.Event.subscribe('auth.sessionChange', function(response) {
    document.location = document.location.href;
});
```

I really suggest not to call isValid on each request! Just check it if you really must be sure, that the user didn't logout by using the logout button on your page.
